name: Test Makefile

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test Makefile
      run: make

  build-arch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: arch-test:latest
      - name: Test Makefile
        run: |
          docker run --rm -v $PWD:/home/testuser/app -w /home/testuser/app arch-test:latest make
            

